### PR TITLE
Streamlining MacOS arm64 build

### PR DESCRIPTION
**Pull request by jdegenstein**
Many changes but was able to successfully build/test for py 3.9 3.10 3.11 and 3.12. I deleted `local-build.sh` and migrated to doing everything in the `local-build.yml` file to have easier use of environment variables (such as the python version). Another benefit of this is that the 4 versions will build in parallel rather than in series.

https://github.com/jdegenstein/ocp-build-system/actions/runs/7804734797

### CODE REVIEW

**Comment by jmwright** [comment]
Thanks for all the work on this @jdegenstein . Would you be able to fix the merge conflicts so that I can merge this?

**Comment by jmwright** [comment]
Maybe we should also leave the local-build.sh script in the repo for people who want to build wheels locally. I have used that script on a RockPro64 to build aarch64 wheels.

**Comment by jmwright** [comment]
Thanks @jdegenstein !

**Comment by jdegenstein** [comment]
@jmwright thanks for merging, sorry I wasn't able to figure out how to fix the merge conflicts (not sure I have permissions to this repo??)

**Comment by jmwright** [comment]
@jdegenstein No problem. You probably could have rebased your branch on main and pushed that back to your fork (you would normally have to do a force push I think). Merge conflicts are a pain though, at least for me, so I understand having trouble with this one.

**Pull request merged**
