### PR TITLE
Try to Test VTK Wheels Before Uploading

### PR DESCRIPTION
**Pull request by jmwright**
I'm trying to replicate what @jdegenstein did ([see comment here](https://github.com/CadQuery/ocp-build-system/issues/30#issuecomment-2183630175)).

### CODE REVIEW

**Comment by jmwright** [comment]
@jdegenstein Do you see any reason why I can't publish the VTK wheels to PyPI at this point?

**Comment by jdegenstein** [comment]
@jmwright no, they look fine to me. Your PR worked perfectly as far as I can tell!

**Comment by jmwright** [comment]
I had to do some manual editing of the package naming. I ended up with `cadquery_vtk-9.2.6-cp311-cp311-linux_x86_64.whl` which also means that the `*.dist-info` directory has to be renamed, and the name entry in the `METADATA` file has to be changed. I think we also need to build Linux ARM64 versions of these wheels too.

**Comment by jdegenstein** [comment]
> I think we also need to build Linux ARM64 versions of these wheels too.

To my knowledge Linux ARM64 runners are not available for free on GH at this time. They have stated they expect them to be available by the end of 2024.

I am not very familiar with controlling the wheel naming/dist-info/METADATA. Does this need to be fixed now, or were you able to just edit them all manually?

**Comment by jmwright** [comment]
> To my knowledge Linux ARM64 runners are not available for free on GH at this time. They have stated they expect them to be available by the end of 2024.

I have an RockPro64 set up so that I can build wheels on it.

> I am not very familiar with controlling the wheel naming/dist-info/METADATA. Does this need to be fixed now, or were you able to just edit them all manually?

I'm considering editing them manually for this release, but I'm a little worried about errors when doing things by hand. I may have a go at getting CI to make the changes with tools like sed.

I should also just add my RockPro64 as a self-hosted runner, but I've never done that before and do not have a lot of spare time at the moment to experiment.

**Pull request merged**
